### ISSUE TITLE
xq

### ISSUE THREAD

**Issue by ArcPav** [iyume/nonebot-plugin-arcaea#1]
大佬有没有XQ的

**Comment by iyume** [comment]
不知道你是不是想说 cqhttp，能否说一下你使用的 SDK (开发框架) 呢

**Comment by ArcPav** [comment]
能不能整成后续名XQ.dll的
我压根就不会用sdk
用的先驱机器人


可以的话请发网盘链接什么盘的都行 不行就算了不强求
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iyume/nonebot-plugin-arcaea"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月22日(星期一) 下午2:44
收件人:&nbsp;"iyume/nonebot-plugin-arcaea"<nonebot-plugin-arcaea@noreply.github.com&gt;;
抄送:&nbsp;"byؼϪ"<arcpav@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [iyume/nonebot-plugin-arcaea] xq (#1)





 
不知道你是不是想说 cqhttp，能否说一下你使用的 SDK (开发框架) 呢

**Comment by iyume** [comment]
结论：这两个是完全不同的东西，目前没有对先驱进行插件开发的打算。

[https://discourse.xianqubot.com/t/topic/50/5](https://discourse.xianqubot.com/t/topic/50/5)

有一种折中的方案是使用 OneBot-YaYa 与 nonebot2 进行通信，这个方法不需要你了解如何开发 nonebot2，只需要设置好通信方式就行了。

**Comment by iyume** [comment]
issue opening :)

**Comment by ArcPav** [comment]
如果大佬将来打算整个请发邮箱通知我 谢谢
