### ISSUE TITLE
后续开发

### ISSUE THREAD

**Issue by RandomEnch** [iyume/nonebot-plugin-arcaea#7]
问一下，这个插件还打算后续开发吗，目前用不了啊

**Comment by iyume** [comment]
请先阅读 #3 #8

此插件不会直接向 616 官方查询游戏数据，所以很少存在版本滞后导致插件无法使用的情况。查询游戏数据的工作在 [BotArcAPI](https://github.com/TheSnowfield/BotArcAPIs-Memories) 之类的完成一个 self-hosted API server，然后再由本插件请求处理。

而现状是，就在我把此插件完成后不久，616 一波智障操作导致其游戏的 API 的解密变得极其困难，目前想要自运营一个查分器是不容易的。

1. 你希望做一个查分器并且能使用 NoneBot 插件将其变成群友的 RBQ

    建议去 BotArcAPI 的群组，我不是很了解 BotArcAPI 的开发现状，#8 中给出的 bilibili 动态是我目前所了解到的现状（极端地说，学习逆向去吧，相信隔壁开发组很需要你。要不然，你无法预测每次的版本更新后，API 会有什么变化以及你能否快速应对。）

2. 你仅希望查询 Arcaea 游戏数据

    直接使用别人的 Arcaea Bot 即可，比如 Discord 下由 Lxns 运营的 Bot。

**Comment by iyume** [comment]
BotArcAPI make private 后 `issue #29` 不知为何消失了，不过 `issue #28` 可以在 https://github.com/TheSnowfield/BotArcAPIs-Memories/ 找到。

**Comment by RandomEnch** [comment]
了解了
